// Generated by https://quicktype.io

export interface UniversityModel {
    alpha_two_code:   string;
    web_pages:        string[];
    name:             string;
    country:          string;
    domains:          string[];
    // state_province:   string;
}

